# Generated by Django 2.1.5 on 2019-01-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20190128_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
