# Generated by Django 2.1.7 on 2019-02-23 19:27

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0038_auto_20190223_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
