# Generated by Django 2.1.7 on 2019-02-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0039_auto_20190223_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='about',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
