# Generated by Django 2.1.7 on 2019-02-24 13:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0041_auto_20190224_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='about',
            field=models.CharField(max_length=600, verbose_name='Sobre você'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('horse', 'Cavalos'), ('rat', 'Roedores')], max_length=100, verbose_name='Selecione seus pets'),
        ),
    ]
