# Generated by Django 2.1.7 on 2019-03-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0048_auto_20190309_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='usuario_id',
        ),
    ]
