# Generated by Django 2.1.7 on 2019-03-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0050_gallery_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='obs',
            field=models.CharField(default=99, max_length=15),
            preserve_default=False,
        ),
    ]
