# Generated by Django 2.1.7 on 2019-03-14 16:00

from django.db import migrations, models
import multiselectfield.db.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0055_auto_20190310_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='estabelecimento',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='negocio',
            old_name='responsavel',
            new_name='proprietario',
        ),
        migrations.AddField(
            model_name='negocio',
            name='cnpj',
            field=models.CharField(default=2, max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negocio',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negocio',
            name='tipo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=2, max_length=100, verbose_name='Tipo de negocio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negocio',
            name='foto',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
