# Generated by Django 2.1.4 on 2018-12-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('pet', models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Passáros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('naosei', 'Cavalos'), ('rat', 'Roedores')], default='dog', max_length=2)),
                ('quantidade', models.CharField(choices=[('one', '1'), ('two', '2'), ('tree', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('more', 'mais de 6')], default='one', max_length=2)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RS', max_length=2)),
            ],
        ),
    ]
