# Generated by Django 2.1.7 on 2019-04-04 11:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaros', 'Pássaros'), ('Peixes', 'Peixes'), ('Reptéis', 'Reptéis'), ('Roedores', 'Roedores')], max_length=255)),
            ],
        ),
    ]
