# Generated by Django 2.1.7 on 2019-03-30 19:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='pet_aceitos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro Pequeno Porte', 'Cachorro Pequeno Porte'), ('Cachorro Médio Porte', 'Cachorro Médio Porte'), ('Cachorro Grande Porte', 'Cachorro Grande Porte'), ('Gato', 'Gato'), ('Pássaros', 'Pássaros'), ('Peixes', 'Peixes'), ('Reptéis', 'Reptéis'), ('Roedores', 'Roedores')], default='dog', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaros', 'Pássaros'), ('Peixes', 'Peixes'), ('Reptéis', 'Reptéis'), ('Roedores', 'Roedores')], max_length=100, verbose_name='Selecione seus pets'),
        ),
    ]
