# Generated by Django 2.1.7 on 2019-03-30 20:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190330_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAceitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_aceitos', multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro Pequeno Porte', 'Cachorro Pequeno Porte'), ('Cachorro Médio Porte', 'Cachorro Médio Porte'), ('Cachorro Grande Porte', 'Cachorro Grande Porte'), ('Gato', 'Gato'), ('Pássaros', 'Pássaros'), ('Peixes', 'Peixes'), ('Reptéis', 'Reptéis'), ('Roedores', 'Roedores')], default='dog', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='negocio',
            name='domingo_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='quarta_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='quinta_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='sabado_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='segunda_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='sexta_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='terca_24',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='N', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='tipo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Hotéis', 'Hotéis'), ('PetShops', 'PetShops'), ('Veterinários', 'Veterinários'), ('Restaurantes', 'Restaurantes'), ('Cafés', 'Cafés'), ('HotéisPet', 'HotéisPet')], max_length=100, verbose_name='Tipo de negocio'),
        ),
    ]
