# Generated by Django 2.1.7 on 2019-04-04 15:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_aceitos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='negocio',
            name='pet_aceitos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], max_length=100, verbose_name='Selecione seus pets'),
        ),
    ]
