# Generated by Django 2.1.7 on 2019-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190317_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='horario_domingo1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_domingo2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_domingo3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_domingo4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quarta1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quarta2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quarta3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quarta4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quinta1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quinta2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quinta3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_quinta4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sabado1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sabado2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sabado3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sabado4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_segunda1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_segunda2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_segunda3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_segunda4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sexta1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sexta2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sexta3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_sexta4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_terca1',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_terca2',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_terca3',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='horario_terca4',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
