# Generated by Django 2.1.7 on 2019-03-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190317_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='data',
        ),
    ]
