# Generated by Django 2.1.4 on 2018-12-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20181219_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimentos',
            name='foto',
            field=models.ImageField(default=1, height_field=500, upload_to='foto_estabelecimento', width_field=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, height_field=300, upload_to='foto_usuario', width_field=300),
            preserve_default=False,
        ),
    ]
