# Generated by Django 2.1.7 on 2019-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20190405_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Chachorro e  Gato', 'Chachorro - Gato')], max_length=255),
        ),
    ]
