# Generated by Django 2.1.4 on 2018-12-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20181221_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estabelecimentos',
            new_name='Negocio',
        ),
    ]
