# Generated by Django 2.1.5 on 2019-01-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20181230_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Passáros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('naosei', 'Cavalos'), ('rat', 'Roedores')], max_length=255),
        ),
    ]
