# Generated by Django 2.1.5 on 2019-01-07 00:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190106_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='pet_aceitos',
            field=models.CharField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('naosei', 'Cavalos'), ('rat', 'Roedores')], default='dog', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('naosei', 'Cavalos'), ('rat', 'Roedores')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='quantidade',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('tree', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('more', 'mais de 6')], default='one', max_length=10),
        ),
    ]
