# Generated by Django 2.1.5 on 2019-01-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20190106_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='foto_usuario'),
        ),
    ]
