# Generated by Django 2.1.5 on 2019-01-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20190106_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='quantidade',
        ),
    ]
