# Generated by Django 2.1.5 on 2019-01-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_remove_usuario_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pet',
        ),
        migrations.AddField(
            model_name='usuario',
            name='quantidade',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('tree', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('more', 'mais de 6')], default='one', max_length=10),
        ),
    ]
