# Generated by Django 2.1.5 on 2019-01-08 23:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20190108_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Cachorro'), ('cat', 'Gato'), ('bird', 'Pássaros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('naosei', 'Cavalos'), ('rat', 'Roedores')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
