# Generated by Django 2.1.5 on 2019-01-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_remove_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, upload_to='foto_usuario'),
            preserve_default=False,
        ),
    ]
