# Generated by Django 2.1.5 on 2019-02-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20190128_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password1',
        ),
    ]
