# Generated by Django 2.1.5 on 2019-01-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20190108_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='foto'),
        ),
    ]
