# Generated by Django 2.1.5 on 2019-02-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_auto_20190201_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name='Foto para seu perfil'),
        ),
    ]
