# Generated by Django 2.1.5 on 2019-02-04 22:43

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_auto_20190203_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=stdimage.models.StdImageField(upload_to=''),
        ),
    ]
