# Generated by Django 2.1.7 on 2019-04-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_auto_20190411_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cnpj',
            new_name='cnpj2',
        ),
    ]
