# Generated by Django 2.1.7 on 2019-04-11 15:25

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_auto_20190411_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=stdimage.models.StdImageField(upload_to='photos/'),
        ),
    ]
