# Generated by Django 2.1.7 on 2019-02-19 16:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0035_auto_20190219_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dog', 'Cachorro'), ('https://www.petz.com.br/blog/wp-content/uploads/2017/07/gato02.jpg', 'https://www.petz.com.br/blog/wp-content/uploads/2017/07/gato02.jpg'), ('bird', 'Pássaros'), ('fish', 'Peixes'), ('rep', 'Reptéis'), ('horse', 'Cavalos'), ('rat', 'Roedores')], max_length=255, verbose_name='Selecione seus pets'),
        ),
    ]
