# Generated by Django 2.1.7 on 2019-03-09 23:16

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0045_auto_20190308_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', stdimage.models.StdImageField(upload_to='')),
                ('titulo', models.CharField(max_length=50)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario')),
            ],
        ),
    ]
