# Generated by Django 2.1.7 on 2019-03-09 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0049_remove_gallery_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
            preserve_default=False,
        ),
    ]
