# Generated by Django 2.1.7 on 2019-03-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0056_auto_20190314_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='senha',
        ),
    ]
