# Generated by Django 2.1.7 on 2019-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190404_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='pet_aceitos',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Chachorro e  Gato', 'Chachorro - Gato')], max_length=255),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='tipo',
            field=models.CharField(choices=[('Hotéis', 'Hotéis'), ('PetShops', 'PetShops'), ('Veterinários', 'Veterinários'), ('Restaurantes', 'Restaurantes'), ('Cafés', 'Cafés'), ('HotéisPet', 'HotéisPet')], max_length=100, verbose_name='Tipo de negocio'),
        ),
    ]
