# Generated by Django 2.1.7 on 2019-04-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20190407_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='galerry_usuario',
            new_name='gallery_usuario',
        ),
    ]
