# Generated by Django 2.1.7 on 2019-04-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='gallery_usuario',
        ),
        migrations.AddField(
            model_name='photo',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Negocio'),
            preserve_default=False,
        ),
    ]
