# Generated by Django 2.1.7 on 2019-04-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20190410_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id_negocio',
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.OneToOneField(default=555, on_delete=django.db.models.deletion.CASCADE, to='sistema.Negocio'),
            preserve_default=False,
        ),
    ]
