# Generated by Django 2.1.7 on 2019-04-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20190410_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cnpj',
        ),
    ]
