# Generated by Django 2.1.7 on 2019-04-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_photo_cnpj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cnpj',
            new_name='user',
        ),
    ]
