# Generated by Django 2.1.7 on 2019-04-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20190410_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='cnpj',
        ),
    ]
