# Generated by Django 2.1.7 on 2019-04-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20190410_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='usder',
            new_name='user',
        ),
    ]
