# Generated by Django 2.1.7 on 2019-04-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0028_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='pet',
            new_name='pets',
        ),
    ]
