# Generated by Django 2.1.7 on 2019-04-21 19:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0029_auto_20190421_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Peixes', 'Peixes'), ('Tartarugas', 'Tartarugas'), ('Hamster', 'Hamster')], max_length=255),
        ),
    ]
