# Generated by Django 2.1.7 on 2019-04-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0032_comentario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nome',
        ),
    ]
