# Generated by Django 2.1.7 on 2019-04-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0035_auto_20190427_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nome2',
        ),
    ]
