# Generated by Django 2.1.7 on 2019-04-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0038_auto_20190428_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
