# Generated by Django 2.1.7 on 2019-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0041_auto_20190428_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
