# Generated by Django 2.1.7 on 2019-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0042_auto_20190428_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
    ]
