# Generated by Django 2.1.7 on 2019-04-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0046_remove_comentario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
            preserve_default=False,
        ),
    ]
