# Generated by Django 2.1.7 on 2019-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0048_auto_20190503_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255),
        ),
    ]
