# Generated by Django 2.1.7 on 2019-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0051_auto_20190508_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
