# Generated by Django 2.1.7 on 2019-05-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0056_auto_20190517_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='domingo_24',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='quarta_24',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='quinta_24',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='sabado_24',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='segunda_24',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='sexta_24',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='terca_24',
        ),
    ]
