# Generated by Django 2.1.7 on 2019-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0057_auto_20190521_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='pet_aceitos',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Cachorro e  Gato', 'Cachorro e  Gato')], max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='about',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pet',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Cachorro e  Gato', 'Cachorro e  Gato')], max_length=255),
        ),
    ]
