# Generated by Django 2.1.7 on 2019-05-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0058_auto_20190528_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
