# Generated by Django 2.1.7 on 2019-06-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0063_auto_20190616_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='domingo',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='quarta',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='quinta',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='segunda',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='sexta',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='terca',
        ),
    ]
