# Generated by Django 2.1.7 on 2019-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0065_negocio_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='cnpj',
            field=models.CharField(max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
