# Generated by Django 2.1.7 on 2019-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0067_auto_20190623_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=19),
        ),
    ]
