# Generated by Django 2.1.7 on 2019-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0068_auto_20190623_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='cnpj',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
